<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_methodNMCK</name>
   <tag></tag>
   <elementGuidId>88f914e0-70f6-4854-9a0b-ed98abc71161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class='table-content']/*[@class='table-edit-row']//button[@id = 'MetodOpredId' and @type = 'button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'MetodOpredId' and @type = 'button' and @class = 'btn btn-default show-dict-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MetodOpredId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default show-dict-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/edo/Dictionary/GetJson?dictionaryName=Метод определения НМЦК&amp;showCodeColumn=False</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fields</name>
      <type>Main</type>
      <value>&amp;dictFieldsInfo={&quot;DictionaryFieldInfoList&quot;:[{&quot;EditName&quot;:&quot;MetodOpredId&quot;,&quot;DictColumnName&quot;:&quot;code&quot;,&quot;ShowAsDisplayText&quot;:false,&quot;DictColumnWidth&quot;:&quot;&quot;,&quot;ShowAsDictionaryColumn&quot;:false},{&quot;EditName&quot;:&quot;MetodOpred&quot;,&quot;DictColumnName&quot;:&quot;Наименование&quot;,&quot;ShowAsDisplayText&quot;:true,&quot;DictColumnWidth&quot;:&quot;&quot;,&quot;ShowAsDictionaryColumn&quot;:true}]}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dict-name</name>
      <type>Main</type>
      <value>Метод определения НМЦК</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regcard-tlcInfo&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row row-container clearfix&quot;]/div[@class=&quot;col-xs-12 column-container&quot;]/div[@class=&quot;table-edit-wrapper&quot;]/div[@class=&quot;table-edit&quot;]/div[@class=&quot;table-content&quot;]/div[@class=&quot;table-edit-row&quot;]/div[@class=&quot;table-edit-columns right-actions-offset&quot;]/div[@class=&quot;table-edit-column text&quot;]/div[@class=&quot;documentView-field-value form-group has-error&quot;]/div[@id=&quot;MetodTab-MetodOpredIdtree&quot;]/span[@class=&quot;input-group-btn&quot;]/button[@id=&quot;MetodOpredId&quot;]</value>
   </webElementProperties>
</WebElementEntity>
