<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LLotOrder</name>
   <tag></tag>
   <elementGuidId>4c70fac2-e85a-479e-ac52-3d672b2f4cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//script[@src='/edo/Scripts/Content/Document/RegCard/LLotOrder.js']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
