<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KTRU</name>
   <tag></tag>
   <elementGuidId>036471c2-3a90-454b-aac8-d74d02b6886d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edo/Administration/Search?searchType=SKTRU&amp;searchBlock=%D0%9A%D0%A2%D0%A0%D0%A3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>КТРУ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>waitingDialog.show('Загрузка');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                КТРУ
                            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-1&quot;)/div[@class=&quot;page-body&quot;]/div[@class=&quot;search-menu-tabs&quot;]/ul[@class=&quot;nav nav-tabs tabs-left&quot;]/div[@class=&quot;nav nav-tabs tabs-left panel-collapse collapse in report-element&quot;]/li[3]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
