<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_priceRequestTRU</name>
   <tag></tag>
   <elementGuidId>d3842b0b-d47e-4e09-bad1-ca35c874dad0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edo/Search/Search?searchType=QueryPrice&amp;searchBlock=%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D1%8B%20%D1%86%D0%B5%D0%BD%20%D1%82%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2%2C%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%2C%20%D1%83%D1%81%D0%BB%D1%83%D0%B3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>waitingDialog.show('Поиск');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Запросы цен товаров, работ, услуг
                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-1&quot;)/div[@class=&quot;page-body&quot;]/div[@class=&quot;container flex-container&quot;]/div[1]/div[@class=&quot;search-menu-tabs&quot;]/ul[@class=&quot;nav nav-tabs tabs-left&quot;]/li[6]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
