<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cod</name>
   <tag></tag>
   <elementGuidId>0f1f1c16-eb15-49a4-aeb3-49dc52de95cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='table-content']/div[@class='table-edit-row'][@data-rowkey='1']//input[contains(@name,'OsnOneWinner-OsnCode')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
