<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>223 Approval contract</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-06T15:52:44</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a69f2736-5893-4d3d-acf3-50f3a671626a</testSuiteGuid>
   <testCaseLink>
      <guid>9f19a021-7c36-44c5-877f-a77e904629d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7443a07c-2b90-4566-ae70-c987ca42044b</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7443a07c-2b90-4566-ae70-c987ca42044b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login</value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60c97b54-c8cb-4bb1-ba6e-50f2208673b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Execution/Route_appruval MyTask</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;S&quot;</value>
         <variableId>eb570175-d756-4780-a309-bef935898472</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>a916303e-e8ad-45c8-a7ae-36078831db91</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
