<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_exit</name>
   <tag></tag>
   <elementGuidId>44119176-4d2a-4da6-bf68-1cb8a2790776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Выход' or . = 'Выход')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Выход']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Выход</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerMenu&quot;)/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[4]/a[1]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
