<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Регистрация пользователя</description>
   <name>Registration testEP_2_user</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-16T14:16:29</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>eadf0464-0d17-449a-9cd8-df0cf40da415</testSuiteGuid>
   <testCaseLink>
      <guid>4db423bf-5cb2-4ddc-812b-7eea7499efba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/Registration</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4735ec21-29e0-4012-bb5c-4e281cb128e8</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>7</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>true</value>
         <variableId>80ca654c-4c31-40ac-bd12-3c0547250c4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10e39d6b-f8de-4def-83d2-9b2eee62d501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4735ec21-29e0-4012-bb5c-4e281cb128e8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Surname</value>
         <variableId>cb5ac666-f12c-4d10-a01c-fdbf7e1833aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4df1d89-f988-4fe7-b107-98ca3ef253f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2dc637d-ebe7-461b-869d-6ceae74ae348</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4735ec21-29e0-4012-bb5c-4e281cb128e8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>5bc4067d-7f04-40db-b5e2-f04f2901a9e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ca04b03-b212-4f02-8ba5-89098d204005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4735ec21-29e0-4012-bb5c-4e281cb128e8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login</value>
         <variableId>23a70d07-4520-4100-8487-0ae58495e300</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97ace46f-95ac-4f1e-9938-fa9dcf786fec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>true</value>
         <variableId>b839600a-fa63-42b1-8f21-c7a026772e8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c83758d5-d305-4b9d-86bc-c03767e4426e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>true</value>
         <variableId>2a3cadba-35fc-48d7-a38b-f101c9775306</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84711138-f970-473b-8e93-65102245a8f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/Activation_mailCognitive</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>52f0ee20-ee9d-4964-ba76-fed2def230f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b1905ac6-565f-4d10-af3f-1a48a594b188</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>4</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b1905ac6-565f-4d10-af3f-1a48a594b188</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login</value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b1905ac6-565f-4d10-af3f-1a48a594b188</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0b0e0e6-89e2-4ab4-9ba2-c107e739f310</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/Activation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7c369e22-ff63-4a27-a4d6-e14185abf1bb</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>7</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7c369e22-ff63-4a27-a4d6-e14185abf1bb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Surname</value>
         <variableId>c8f11777-68f6-415a-a4fa-a4d06962d858</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107b3527-ae95-472e-8ae7-6084b1207b23</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
