<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_codPurchase</name>
   <tag></tag>
   <elementGuidId>28dcfffe-67b7-48b7-a0c2-83ca4ae39c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='table-content']/div[@class='table-edit-row'][@data-rowkey='1']//button[@id='registerSpZakup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
