<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>act_approval</name>
   <tag></tag>
   <elementGuidId>033ad493-6979-44b3-8df7-3e992d2cb078</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-menu-item-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Утвердить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dx-422762a9-ffe2-8268-8ecf-f51cd8ed516b&quot;)/div[@class=&quot;dx-submenu&quot;]/ul[@class=&quot;dx-menu-items-container dx-menu-no-icons&quot;]/li[@class=&quot;dx-menu-item-wrapper&quot;]/div[@class=&quot;dx-item dx-menu-item dx-menu-item-has-text dx-state-hover&quot;]/div[@class=&quot;dx-item-content dx-menu-item-content&quot;]/span[@class=&quot;dx-menu-item-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
