<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>act_menu</name>
   <tag></tag>
   <elementGuidId>73ba8805-dd7e-4c3a-9377-024ce144aa2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'dx-menu-item-popout-container']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'dx-datagrid-content')]//span[contains(@class,'dx-menu-item-popout-container')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dx-menu-item-popout-container</value>
   </webElementProperties>
</WebElementEntity>
