<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Activation testEP_2_user</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-16T10:58:27</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>24867c3e-4486-427d-946b-4bc54ffdefdd</testSuiteGuid>
   <testCaseLink>
      <guid>4f6fe316-caef-42bc-b14d-57d815f9cd91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ca393e87-a8d2-4bae-99db-5a0f4de9dc17</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>4</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ca393e87-a8d2-4bae-99db-5a0f4de9dc17</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login</value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ca393e87-a8d2-4bae-99db-5a0f4de9dc17</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bb0f292-9c4e-4516-ae7a-276a3b26d98d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Registration/Activation</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>85afc6fd-7877-4e8f-914d-e6f1ae3f13ae</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>7</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>85afc6fd-7877-4e8f-914d-e6f1ae3f13ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Surname</value>
         <variableId>c8f11777-68f6-415a-a4fa-a4d06962d858</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107b3527-ae95-472e-8ae7-6084b1207b23</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
