<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_workGroup</name>
   <tag></tag>
   <elementGuidId>841dcb97-eabd-4037-a07c-f51623273b2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;WorkGroup_chosen&quot;)/ul[@class=&quot;chosen-choices&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='WorkGroup_chosen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-choices</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WorkGroup_chosen&quot;)/ul[@class=&quot;chosen-choices&quot;]</value>
   </webElementProperties>
</WebElementEntity>
