<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_schedulePlan</name>
   <tag></tag>
   <elementGuidId>3a9a51ec-5f35-4a19-92c4-7d3193a5f0f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/edo/Search/Search?searchType=LSchedulePlanakt&amp;searchBlock=%D0%9F%D0%BB%D0%B0%D0%BD%D1%8B-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B8' and (text() = '
                            Планы-графики
                        ' or . = '
                            Планы-графики
                        ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'search-menu-tabs')]//a[contains(text(),'Планы-графики')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edo/Search/Search?searchType=LSchedulePlanakt&amp;searchBlock=%D0%9F%D0%BB%D0%B0%D0%BD%D1%8B-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA%D0%B8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>waitingDialog.show('Поиск');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Планы-графики
                        </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-1&quot;)/div[@class=&quot;page-body&quot;]/div[@class=&quot;container flex-container&quot;]/div[1]/div[@class=&quot;search-menu-tabs&quot;]/ul[@class=&quot;nav nav-tabs tabs-left&quot;]/li[5]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
