<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_paymentAmount</name>
   <tag></tag>
   <elementGuidId>27ba19bf-b8d1-4c56-97c5-a71bc7ce73ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-rowkey='1']//input[contains(@name,'Positions-SumOpl')][not(contains(@name,'Positions-SumOplRub'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
