<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Route_approvalS MyTask</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-06T11:29:20</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c0162604-1d55-47f7-86a5-beef9dcf215f</testSuiteGuid>
   <testCaseLink>
      <guid>c1a9a956-144f-4793-9a56-e44ad18f797d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>058e32ca-7c31-4f08-9e15-aab14be1fa25</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>058e32ca-7c31-4f08-9e15-aab14be1fa25</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login</value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad890802-f5f1-46c6-995e-a391e0cc7021</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Execution/Route_appruval MyTask</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;S&quot;</value>
         <variableId>eb570175-d756-4780-a309-bef935898472</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>a916303e-e8ad-45c8-a7ae-36078831db91</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
