<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_2018</name>
   <tag></tag>
   <elementGuidId>a68425e8-a136-4c7d-b82e-30842b409f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input
[@value = '2018']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='2018']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2018</value>
   </webElementProperties>
</WebElementEntity>
