<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Change_profile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-23T08:39:01</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>677c3628-927d-40a3-9342-118454e961ac</testSuiteGuid>
   <testCaseLink>
      <guid>30a8bc02-886f-49a5-adbe-334720e9fb0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b1e4e09b-07e7-4612-bb16-596dc0b2ce87</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/Test data.xlsx/Tab_Variables_User</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b1e4e09b-07e7-4612-bb16-596dc0b2ce87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Login</value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59df74a4-5734-4d2f-a025-8cedb20e4ca3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Profile/Change_profile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ca850d7-fbaa-4474-8488-a8af4ad3f3d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c875772-7de5-499f-878d-8c2fe19e6aee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8565d18c-3db9-403a-a413-6ac914430d66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3372be9e-e590-4e51-b295-db0490769aff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0b977d7-cd2c-4c68-a7f0-3757810e2a79</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
