<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create purchase plan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-28T14:54:27</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d84f312f-a03e-4635-a305-27f419aa12a9</testSuiteGuid>
   <testCaseLink>
      <guid>fd7b1aa2-c637-4a86-93b3-29143f184d0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c62a003-3253-4306-beb2-bc5000c4884d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Purchase plan/Create purchase plan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46c12100-4450-432b-902e-94feb96d0a58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b715db9-857f-4149-a8c3-d6e1d6ffcf25</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
