<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create schedule plan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-16T17:30:25</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b6f5f31e-1ab2-438d-8b75-3abba9c99ad9</testSuiteGuid>
   <testCaseLink>
      <guid>df478cd2-ca70-4019-b254-f1c594b09ec1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BASE/Authorization</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17b320b1-1dc6-4561-8e3f-9e6d2173db87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9fed6bf-a35f-4c63-9a99-5bc306f5c375</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c4cdd5-2da3-43dd-8599-604e181b2311</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52e34265-73ff-4370-903a-954ca93c4d7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Schedule plan/Create schedule plan</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35c07961-be37-467d-b1e0-ce597d549c11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e793436-18f4-4505-8eb5-01999f3995cc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
