<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_urlPPZ</name>
   <tag></tag>
   <elementGuidId>d09fc6db-0958-44f6-b7f5-0b43205db756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Пшеница' or . = 'Пшеница')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Пшеница')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-result-cell-value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edo/Document/DocumentView/31618</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Пшеница</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Пшеница</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;links-table-92d94f06-8689-4184-b20b-571c49ebfa95&quot;)/div[@class=&quot;dx-datagrid&quot;]/div[@class=&quot;dx-datagrid-rowsview dx-datagrid-nowrap dx-scrollable dx-scrollable-customizable-scrollbars dx-scrollable-both dx-scrollable-simulated dx-visibility-change-handler&quot;]/div[@class=&quot;dx-scrollable-wrapper&quot;]/div[@class=&quot;dx-scrollable-container&quot;]/div[@class=&quot;dx-scrollable-content&quot;]/div[@class=&quot;dx-datagrid-content&quot;]/table[@class=&quot;dx-datagrid-table dx-datagrid-table-fixed&quot;]/tbody[1]/tr[@class=&quot;dx-row dx-data-row dx-column-lines&quot;]/td[@class=&quot;dx-sortable-column&quot;]/div[@class=&quot;search-result-cell text&quot;]/a[@class=&quot;search-result-cell-value&quot;]</value>
   </webElementProperties>
</WebElementEntity>
